### ISSUE TITLE
Fraud Monitor Triggers

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#16]
- [x] New possible fraudulent purchase

**Comment by SDavisMedia** [comment]
Suspected Fraud trigger working perfectly. Also properly triggered the Purchase Complete trigger after being marked as valid. :+1:

**Comment by pippinsplugins** [comment]
I'm not seeing this. I have Fraud Monitor active but there's no trigger for it for me.

**Comment by pippinsplugins** [comment]
<img width="1001" alt="screen shot 2017-07-19 at 4 18 04 pm" src="https://user-images.githubusercontent.com/1034109/28389984-dbde953a-6c9d-11e7-9ca5-09d2aa984346.png">

**Comment by d4mation** [comment]
Shows for me.

EDD Slack `release/v1.1` at commit 8463a8b0d20050019a67a9eeaf291dc4556da799
Easy Digital Downloads at tag `2.8-beta2`
Fraud Monitor v1.0.3

![image](https://user-images.githubusercontent.com/7770631/28390180-fd824fde-6ca6-11e7-819a-a17131ff633c.png)

**Comment by pippinsplugins** [comment]
Ah! Sorry, 100% user error. Ignore me :D

**Comment by pippinsplugins** [comment]
:)

**Comment by pippinsplugins** [comment]
The trigger showed up for me now but I can't get it to trigger. 

I'm seeing this notice over and over:

Jul 19, 21:30:06
PHP Notice: Undefined property: stdClass::$members in /Users/pippin/Sites/edd/wp-content/plugins/edd-slack/core/edd-slack-functions.php on line 40
Jul 19, 21:30:06
PHP Warning: Invalid argument supplied for foreach() in /Users/pippin/Sites/edd/wp-content/plugins/edd-slack/core/edd-slack-functions.php on line 43

**Comment by d4mation** [comment]
That seems to be related to the OAUTH Functionality failing to grab a list of Slack Users. 

Just to help rule things out, could you try going to the [users.list](https://api.slack.com/methods/users.list/test) Test page and set it up like the following and let me know what the results are?

`token` -> `No Token`
`Extra args` -> `token=<your_oauth_token>`

You can get your OAUTH Token by running

`edd_get_option( 'slack_app_oauth_token' );`
