### ISSUE TITLE
Reviews Triggers

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#19]
- [x] New review
- [x] New Vendor Feedback (Also Requires FES. Referencing #46)

See #4 for some blocking issues with this Integration

**Comment by SDavisMedia** [comment]
I take it this is no longer blocked by anything in #4?

Both triggers working perfectly for me. :+1:

**Comment by d4mation** [comment]
It isn't blocked, but due to the way the Hooks are set up in Reviews I cannot take advantage of the sanitization done as the Review is created. I had to copy-paste the same code in order to replicate any changes that Reviews would have made to the Review as it is being saved. 

So, it works, but it isn't 100% ideal. If some additional Hooks were added after all the processing is done and it is saved to the database, the data sent out to Slack would be "more accurate". My only real concern is that since I had to copy/paste that code, if it were to change in Reviews I'd have to copy/paste it again.
