### ISSUE TITLE
Multi-Select for Downloads Field

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#31]
This way the User does not have to make Multiple Triggers to watch maybe 2 or 3 Downloads if they don't want to.

~~Could be good to have for the Discount Code field as well.~~ This is going to be its own Issue. Forgot I put this here and Multi-Select for Downloads was enough of a chore to implement 🤐

**Comment by d4mation** [comment]
Progress toward this is being made.

Having some odd UI problems for the Notification creation that I'm working out, but the actual functionality for it has been built out for the "base" Notification Triggers.

If "All Downloads" is selected as the Download, then an Exclusion Field appears which can be used to exclude certain Downloads from triggering the Notification.

This all works with Variations as well.

There is one oddity that I'm confused with how to handle:

Right now if "All Downloads" is selected, I'm forcing the user to click the "x" to remove it before selecting any other Downloads. This is to prevent stupid selections like "All Downloads" and "Some other Download" at the same time. However, there's no feedback to the user about why what they're doing is dumb. Might need to find a way to provide that.

I could program it to simply ignore any other choices if "All Downloads" is selected, but I'd rather just disallow it. I'd rather not let the UI make the plugin appear "hacky" by allowing bad input like that, even if it were to be ignored.

![image](https://user-images.githubusercontent.com/7770631/28851394-1846331e-76f0-11e7-8e85-a0a3447bf2dc.png)

**Comment by brashrebel** [comment]
Very good thinking ahead like that. It sounds like a fairly small issue currently. I think we open a new issue and milestone it for later.

**Comment by d4mation** [comment]
Turns out part of the quirks I ran into were EDD-related, actually. Time for a PR~

**Comment by d4mation** [comment]
This is all implemented now within the `release/v1.1` branch :+1:

Although I tested the "Base" Triggers, I have not tested any of the others that are dependent upon different Integrations being present. However, the rewrites necessary for the other Triggers were very minor in comparison to the Base Triggers to be honest to the point where I'm not horribly worried about them.

Regardless, some testing to ensure that Multiple Downloads and Exclusions are working properly would be appreciated.

The following Triggers allow specifying a Download ("Base" Triggers are Bolded):
- **Purchase Complete**
- **Purchase Failed**
- **Discount Code Applied**
- New Comment on Download
- New Commission
- Suspected Fraudulent Purchase
- Purchase Limit Reached
- New Subscription Created
- Subscription Cancelled
- New Review on Download
- New Vendor Feedback
- New License Key Generated
- License Key Activated
- License Key Deactivated

--- 

# Note

There is a slight rendering bug related to easydigitaldownloads/easy-digital-downloads#5918. If a Variant is chosen within the Downloads/Exclusions menu and then the changes are changed, on Page Refresh it will also select the "All Variants" option for that Download. Unless the Form is saved with that errant data present it will not cause any problems. However, it could prove problematic as if that does get saved, it will not cause the Notification Filtering/Bailing to work as the User expects. 

> "I only wanted Variant 1 to Trigger the Notification, but after I went back in to change the Title of the Notification now all the Variants are Triggering the Notification. What gives?"

**Comment by d4mation** [comment]
Oh, also, I improved the All Downloads toggling to be much more clear. It shouldn't need a little message any longer :+1:

**Comment by d4mation** [comment]
Some specific things that should be checked:

1. What happens if you try to select "All Downloads" on an already Saved Notification that has specific Downloads set?
2. What happens if you try to select specific Downloads on an already Saved Notification that has "All Downloads" set?
3. What happens if you try to select "All Downloads" on a New (Just Created by hitting "Add Notification", but not saved) Notification that has specific Downloads set?
4. What happens if you try to select specific Downloads on a New (Just Created by hitting "Add Notification", but not saved) Notification that has "All Downloads" set?

I think I addressed all of those use cases, but I'm not sure. I had some weird bugs while testing all of this as part of easydigitaldownloads/easy-digital-downloads#5918, so make sure as well that you're on my Fork for the time being while testing this specific feature :+1:

**Comment by d4mation** [comment]
There may be a bug with Exclusions when it comes to Downloads with Variations. 

I set up a special "Purchase Complete" Notification for Client Dash Pro on RBP for kicks and giggles and have the generic "Purchase Complete" Notification set to exclude it.

There've been at least 2 purchases since then and they did not trigger within Slack (I checked the Slack chat logs to confirm). 

We'll want to ensure something like the following gets tested thoroughly for this:

- All Downloads _except_ All Variants of Download X for a Base Trigger
- All Variants of Download X for the _same_ Base Trigger

"Base Triggers" are bolded in the list a few comments above.

**Comment by d4mation** [comment]
This is because when it checks for the Price ID, All Variants is being stored as `int 0` and it checks a diff against the purchased variant, `int 1` or something similar. The diff says it doesn't exist, so it bails.

Need to make sure it accounts for "All Variants" properly.

**Comment by d4mation** [comment]
This bug is now fixed. At the very least for Base Triggers.

However, considering the Base Triggers had much more complicated logic that another other Trigger (Other Triggers don't touch the Cart) it should be fine.
