### ISSUE TITLE
Activate License Trigger is broken

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#51]
My guess is EDD Software Licensing updated and broke something within this trigger for EDD Slack.

realbigplugins/client-dash-pro#12

**Comment by SDavisMedia** [comment]
I can't seem to get this trigger to work on `issue/51/activate-license`. I definitely replicated the fact that it doesn't work as I continuously failed trying to test #59. Once I realized this was an issue and checked out `issue/51/activate-license`, I still can't get it working.

This is all local. Activations are working with `http://localhost/edd/?edd_action=activate_license&item_name=basic+download&license=25c59eef5f3b125f8d2fa4b0afa04f73&url=http://test.com`. There's just no Slack notification. Any ideas?

**Comment by d4mation** [comment]
Have you tried `release/v1.1`? It is possible that I hot-fixed something for this that did not end up in the `issue/51` branch. Everything for v1.1 is in the release branch.

**Comment by SDavisMedia** [comment]
@d4mation Kyle just let me know everything is merged into the release branch already. Just tested there and it still doesn't seem to be sending the notification, though. 

A basic trigger like Purchase Complete is working just fine, so all is connected. Not sure why this notification isn't coming through on `release/v1.1`, though.

**Comment by d4mation** [comment]
I just tested this locally on the `release/v1.1` branch and it appears to work for me.

I have two local environments set up. One which houses EDD+EDD Slack+EDD Software Licenses, and other where I'm activating the License.

I set up Activate/Deactivate License Triggers on the EDD Install and made sure that the plugin which I was activating a License On on the other Install had the Store URL set to point to my local EDD install (In this case, `http://edd.dev`).

Once I did that, activating and deactivating the License sent me notifications just fine.

With the URL you're hitting though does seem like it should be working. Could you paste in your EDD System Info? I don't have the ability to easily pull in any new releases of Software Licenses locally since I do not have access to the Repo for it, so it is possible something updated (again) which broke this trigger.

![image](https://user-images.githubusercontent.com/7770631/27345402-8aa0daae-55b7-11e7-8a29-b0064cce23c7.png)

![image](https://user-images.githubusercontent.com/7770631/27345361-6901b31e-55b7-11e7-9736-2c968d0a2785.png)

**Comment by SDavisMedia** [comment]
Does it still work if just use query vars to activate/deactivate? `http://localhost/edd/?edd_action=activate_license&item_name=basic+download&license=25c59eef5f3b125f8d2fa4b0afa04f73&url=http://test.com`

---

[edd-system-info.txt](https://github.com/realbigplugins/edd-slack/files/1089050/edd-system-info.txt)

**Comment by d4mation** [comment]
I just tested it by using the URL directly and it worked for me. 👍 

I'm running Software Licenses v3.5.4 and it looks like you're using v3.5.14. If you are able, could you roll back to v3.5.4 and see if it works so we can rule out any other environment differences? I'll see if I can get ahold of v3.5.14.

**Comment by SDavisMedia** [comment]
@d4mation shoot me your email. Doesn't appear to be on your GitHub profile. I'll test 3.5.4 too.

**Comment by d4mation** [comment]
Work email is: eric@realbigmarketing.com

**Comment by SDavisMedia** [comment]
You should be receiving a Dropbox notification since gmail will most likely beef with the included JS files.

**Comment by SDavisMedia** [comment]
Still not working for me on 3.5.4. Perhaps it's environmental. Should get a test from @brashrebel.

**Comment by d4mation** [comment]
Yeah, that's weird. I just tested v3.1.14 and it still works on my end. Something must be causing it to error out silently as it is processing the Notification, but only for Activation/Deactivation of Licenses.

If that's the case, placing this at Line 362 of `./core/slack/class-edd-slack-notification-integration.php` should allow us to figure out what's going on.

```
ob_start();
var_dump( $message );
$contents = ob_get_clean();

file_put_contents( EDD_Slack_DIR . '/error.txt', $contents );
```

I did notice that I mistyped earlier and you were actually running v3.5.15, but if it doesn't work for you on v3.5.4 it is likely something else rather than a patch on Software Licenses breaking it.

**Comment by brashrebel** [comment]
I'll give it a test now.

**Comment by brashrebel** [comment]
Now I finally got this to work. I must have been doing something wrong before like testing licenses that were somehow invalid or with the wrong product name or I don't know what. But I just made a new purchase and tested via the URL with a new license and it worked.
