### ISSUE TITLE
Automated Slack Team invites

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#54]
- automated invitations for approved vendors
- automated invitations for customers
- manual invitation of vendors
- manual invitation of customers
- settings for enabling automated invitations

This would be really cool for notifying Users of new Downloads (If a "New Download" Trigger were added)

It could also potentially do cool things with realbigplugins/learndash-slack#4

Look into seeing if Invites can auto-invite Users into Channels. - Edit: They can

**Comment by pippinsplugins** [comment]
Is this all in `release/1.1`? I can't find the settings for it.

**Comment by d4mation** [comment]
It is. It requires SSL on the site and you also have to run through a secondary OAUTH to grant extra permissions.
