### ISSUE TITLE
Notification modal just freezes Save button if hit prematurely

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-slack#73]
If I have not filled out a required field and try to save a notification, the validation stops me as it should. However, the button then stays in the "Saving..." state until I close the modal and reload the page or hit save changes at which point my progress is lost.

**Comment by d4mation** [comment]
Huh, good catch! I'll get that patched out.

**Comment by d4mation** [comment]
Hotfixed this on a local branch and merged it into `release/v1.1`. If you pull the latest changes on that branch this should no longer be an issue :+1:

**Comment by brashrebel** [comment]
Confirmed fixed!
