### ISSUE TITLE
Add some text to settings page describing the need to use SSL

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-slack#74]
Some features of this plugin require SSL. But if a user doesn't read the product page or the docs (which is most users) they won't know about this requirement. I think we should add the following text:

> Your site is not using SSL. To enable advanced features please install an SSL certificate.

Not sure what the best wording is honestly. @SDavisMedia might have a better idea. He often does. And he might even be one of those people unaware of the need for SSL to do anything beyond basic notifications.

**Comment by SDavisMedia** [comment]
I'm aware, only because I tested EDD Slack heavily before it was released. I think the text should only tell them what they don't know.

> To enable advanced features, please install an SSL certificate.

I honestly think that that does the trick.

**Comment by d4mation** [comment]
Handled similarly in c7f2e225de975d9b61dfeb9a88275c95476245e2. 

Didn't see this Issue before I addressed this as I did it after talking to @brashrebel on Slack so the wording is a bit different. It directs the user to the Docs for more details on the SSL-only features.

**Comment by brashrebel** [comment]
Current text:

> Some extra functionality is available only for SSL-enabled sites. Please see the Documentation for more details.

Might not have capitalized the Documentation or included the word "extra" but am otherwise content with this phrasing.

**Comment by d4mation** [comment]
Removed "extra" and lowercased "Documentation" :+1:
