### ISSUE TITLE
Use new Select Multiple in EDD v2.8

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#75]
Yay, we don't have to do it my dumb way anymore!

**Comment by d4mation** [comment]
Since the `release/v2.8` branch of EDD does not have the `EDD_VERSION` Constant updated yet, this means EDD Slack currently _will not_ work correctly. This is _expected behavior_.

For testing purposes, you can define the `EDD_VERSION` constant to be `2.8` or higher and it will cause EDD Slack to work as expected.

**Comment by brashrebel** [comment]
I don't remember what this was like before but the select multiple works great for downloads.

**Comment by d4mation** [comment]
This was originally opened due to the Customer Invite functionality and the Slash Command Restriction functionality (both SSL-only) used Select Multiple for selecting Slack Channels and Slack Users respectively. I had implemented a custom Select Multiple field type at first since Select Multiple wasn't a thing in the Settings API until EDD v2.8, but then swapped it out with this Issue. It ended up getting used for Multiple Downloads and Download Exclusions as well though later. 👍
