### ISSUE TITLE
Use customer info instead of name / email from user

### ISSUE THREAD

**Issue by pippinsplugins** [realbigplugins/edd-slack#77]
When creating notifications, the following tags are available:

%username% : Display the user's username
%email% : Display the user's email
%name% : Display the user's display name

EDD is trying to get 100% away from ever using the information stored on the WP_User object as that doesn't exist for every customer.

Instead of using WP_User, all EDD extensions should use the EDD_Customer object that is associated with the event / payment.

We should also always use `customer` instead of `user` when referring to the customer.

**Comment by d4mation** [comment]
These are programmed in such a way that if a User object isn't associated with the Customer it instead falls back to the Customer object. So, as it is now, it does work in all situations.

If they are not a User but only a Customer, it will still show their Email and Name correctly. It will just fill the Username Merge Tag with generic "This Customer is not associated with a User" text.

EDD Slack could be changed to _only_ return Customer-related information though.

https://github.com/realbigplugins/edd-slack/blob/cd5a9a3a8392e516f0cfeb00cc20e76f59104e29/core/slack/class-edd-slack-notification-integration.php#L208-L213

**Comment by pippinsplugins** [comment]
I'd like to see it _only_ use customer in all instances except when an event is directly related to a user, such as a new account being created.

**Comment by d4mation** [comment]
That's more or less how it works, actually.

For example, here's the data sent to EDD Slack's Notification System on Purchase Complete:

```
$purchase_args = array(
    'user_id' => $customer->user_id, // If the User isn't a proper WP User, this will be 0
    'name' => $customer->name, // Fallback if there's no associated User ID
    'email' => $customer->email, // Fallback if there's no associated User ID
    'payment_id' => $payment_id,
    'discount_code' => $payment_meta['user_info']['discount'],
    'ip_address' => get_post_meta( $payment_id, '_edd_payment_user_ip', true ),
    'cart' => wp_list_pluck( $cart_items, 'item_number', 'id' ),
    'subtotal' => edd_get_payment_subtotal( $payment_id ),
    'total' => edd_get_payment_amount( $payment_id ),
);
```

If the Customer isn't associated with a WP User, it passes 0 by default. In the event that `user_id` is 0, EDD Slack uses the Customer Name and Customer Email for the `%name%` and `%email%` merge tags instead.

I can change up that conditional slightly so that the Name/Email is _always_ Customer Name/Customer Email outside of those edge-cases where a Customer may not be associated yet (Like Account Creation).

**Comment by brashrebel** [comment]
That sounds good to me.

**Comment by pippinsplugins** [comment]
I'm fine with that.

**Comment by d4mation** [comment]
Customer Info is now used in preference to User Info in every case. I tested it on a few Triggers and it appears to be working correctly. The "User Hints" are used by basically every trigger, so if one works they all should work 👍

**Comment by brashrebel** [comment]
Confirmed, this looks good to me.

**Comment by pippinsplugins** [comment]
:+1:
