### ISSUE TITLE
PHP notices on settings

### ISSUE THREAD

**Issue by pippinsplugins** [realbigplugins/edd-slack#79]
The following notices are showing up on the settings screen for me.

<img width="1777" alt="screen shot 2017-07-19 at 3 54 28 pm" src="https://user-images.githubusercontent.com/1034109/28389157-9d72dc64-6c9a-11e7-8a66-8385037e58c2.png">

**Comment by d4mation** [comment]
@pippinsplugins Are you at the latest commit for `release/v1.1`? I could have sworn I specifically made sure `multiple` would be set in preparation for EDD v2.8.

I'll look into that undefined Constant as well. That shouldn't be there.

**Comment by d4mation** [comment]
I cannot find that Constant in that file either at the latest commit of `release/v1.1`. Although, I also cannot find a commit that would match that error 🤔

**Comment by pippinsplugins** [comment]
Ignore me, I was on the wrong branch.
