### ISSUE TITLE
Row Titles not updating with Notification Identifier correctly

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/edd-slack#82]
Appears to correct itself after page refresh, so this should be exclusively a JavaScript problem

**Comment by brashrebel** [comment]
Not a lot of detail here but couldn't replicate any problem on `release/1.1`

**Comment by d4mation** [comment]
Basically, if you renamed a Slack Notification and hit "Save", it wouldn't update the name of it within the main Settings Page unless you refreshed the whole page. 

If you didn't notice that happening, it should be good.

**Comment by d4mation** [comment]
This also happened if you went to Edit a notification and then closed the Modal. It would reset the Title to the Default (New Slack Notification). 

I ended up patching this same thing in EDD Fields yesterday afternoon.
