### ISSUE TITLE
PHP errors when posting a new comment

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-slack#85]
Just setup a comment notification and got this: https://cloudup.com/cJc1_H3o7co

That happened after saving the notification and then leaving a comment on a download. The notification did send to Slack successfully.

**Comment by brashrebel** [comment]
Same for new and existing users.

**Comment by d4mation** [comment]
Turns out this was caused by a tiny typo. It actually effected a few Integrations since I had copy/pasted that Typo across them.

Should be good now, but could you test the `release/v1.1` branch to confirm? This was related to Download Exclusions.
